---
title: "Take-home - problem set 2"
author: "Clarence Koehle & Yooby Gigandet"
output: pdf_document
---

**1-**

a) 

First of all, as the mugs are randomly given to half of the subjects and the pens to the remaining half, the neoclassical economic model predicts that half of the subjects will trade. It is based on the fact that the assignment is randomly made. Therefore, you get 50% chance to assign the right object to the right subject. Another aspect is that under the neoclassical economics, individual are "rational" thereby they make decision based on maximization of their utility, thereby the percentage of individual choosing to exchange their goods should have far exceed what was found in this study due to the monetary increased added to the goods swap. 


b) 

The neoclassical economic model predicts that half of the subjects will trade. However, only 12% of those who originally received a mug and 10% of those who originally received a pen chose to exchange it for the other item plus 5 cents. It is due to the endowment effect which is explained by the reference-dependent preferences and loss aversion.

Those who received the mugs randomly have their reference point shifted. Their reference point is now: owning the mug. As we have already seen, losses loom larger than gains. In this case, the non-utility of loosing the mug is bigger than the utility of gaining the pen plus 5 cents. The same applies to those who received the pens randomly but in this case, their reference point is now: owning the pen.

In conclusion, reference-dependent preferences and loss aversion explain the experimental results (less trades occur).

c) 

**think we need to use FOC**
Standard utility function (Koszegi and Rabin 2006): 

$$u(c|r) = m(c) + n(c|r)$$
Where:
c = consumption of goods (can be k dimensional);
m(c) = utility derieved by consumption of goods;
n(c|r) = gain-loss utility

In our case:
$$(4c1+4c2+c3)+(v(4c1-r1)+v(4c2-r2)+v(c3-r3))$$
$$ v(x) = \begin{cases} x\space for\space x > 0 \\ 3x \space for\space x <0 \end{cases} $$
Where:
$C = (4c1+4c2+c3)$;
$m(c,w) = (4c1+4c2+c3)+w $
$n(c|r) = (v(4c1-r1)+v(4c2-r2)+v(c3-r3))$

- mugs  : Dimension 1 ; ouctome c1 ; reference r1
- pens  : Dimension 2 ; outcome c2 ; reference r2
- money : Dimension 3 ; outcome c3 ; reference r3

Let's imagine a situation where the agent owns a mug and do not expect to sell it, his reference point will be $(r1,r3) = (1,0)$,
on the other hand in a situation for an agent who neither own nor wants to acquire a mugs while a reference point of $(r1,r3) = (0,0)$. We now can estimate at which compensation price $p^s$ our agent would be indifferent in between changing his mug or not.

$$u((1,0,0)|(1,0,0)) = m(4_{1})+m(0_{2})+m(0_{3}) = 4$$
$$u((1,0,1|(1,0,0) = m(0_{1}) + m(0_{2}) + m(p^s_{3}) + v(m(0_{1}) - m(1_{1})) + v(m(p^s_{3})-mc(0_{3}) \\ = 4(0) + p^s + 3[4(0)-4(1)]+p^s \\ = 2p^s -12$$
$$u((1,0,0|(1,0,0)) =u((1,0,1|(1,0,0) \\ 4 = -12 + 2p^s \\ p^s = 8$$
Now lets take a look at an agent who does not own a mug nor does expect to acquire own.
$$u((0,1,0|(0,1,0)) = m(0_{1}) +m(1_{2}+ mc3(0) = 0 + 4 + 0 = 4$$
$$u(1,0,1|(0,1,0) = m(1_{1}) + m(1_{3})(-p^b + v(mc1(1) - mc1(0)) + v(m(-p^b_{3})-m(0_{3})\\ = 4(1)-p^b1+(4(1)-0)+3[-p^b-0] \\ = 8 - 4p^b \\ p^b = 4$$ 
Because mugs and pens are equal in initial value: $4c1 = 4c2\space;c1 = c2$ We don't need to redo the experience with pens. In this situation we can see that the perceived value of the mug is 2 times higher for the agent owning, this situation is in coherence with the principle of loss aversion. Thereby we can conclude than the formulation provide does capture loss aversion in agents. However this situation is only the case if the initial reference point is "not expected to swap". 
This models also capture diminishing sensitivity (the sensitivity decreased as value of the monetary gains increased). In the example above the monetary gains use was equal to 1 and the ration gain/loss was 2. With a the monetary compensation of 5 cents:
$p^s = 160\space and\space p^b = 40$
The increases in ratio is in coherence with diminishing sensitivity. 
 
 
d) 

The reference points are ($r_1$, $r_2$, $r_3$) = (1, 0, 0). 

Her utility if she keeps the mug is given by:
$$
u((1,0,0)|(1,0,0)) = 4 * 1 + 4 * 0 + 0 + v(4 * 1 - 4 * 1) + v(4 * 0 - 4 * 0) + v(0 - 0) 
$$
$$
u((1,0,0)|(1,0,0)) = 4
$$

Her utility if she exchange the mug for a pen plus $3

$$
u((0,1,3)|(1,0,0)) = 4 * 0 + 4 * 1 + 3 + v(4 * 0 - 4 * 1) + v(4 * 1 - 4 * 0) + v(3 - 0)
$$

$$
u((0,1,3)|(1,0,0)) = 4 + 3 - 12 + 4 + 3 = 2
$$

Therefore as

$$
u((1,0,0)|(1,0,0)) = 4 > 2 = u((0,1,3)|(1,0,0))
$$

an owner of mug will not exchange it for a pen plus $3.

e)

The reference points of a owner of pen are ($r_1$, $r_2$, $r_3$) = (0, 1, 0)

Her utility if she keeps the pen is given by:

$$
u((0,1,0)|(0,1,0)) = 4 * 0 + 4 * 1 + 0 + v(4 * 0 - 4 * 0) + v(4 * 1 - 4 * 1) + v(0 - 0) 
$$
$$
u((0,1,0)|(0,1,0)) = 4
$$

For her to exchange the pen for the mug and an amount of $x$ dollars, we must satisfy the following inequation:

$$ 
u((1,0,x)|(0,1,0)) > u((0,1,0)|(0,1,0))
$$
$$
u((1,0,x)|(0,1,0)) = 4 * 1 + 4 * 0 + x + v(4 * 1 - 4 * 0) + v(4 * 0 - 4 * 1) + v(x-0)
$$
$$
u((1,0,x)|(0,1,0)) = 4 + x + 4 - 12 + x = 2x - 4
$$

Putting this result in the previous equation, we obtain:

$$ 
u((1,0,x)|(0,1,0)) = 2x - 4 > 4 = u((0,1,0)|(0,1,0))
$$

$$
2x > 8
$$
$$
x > 4
$$

Hence, a pen owner must be paid more than $4 to agree to exchange it for a mug.

f)

If she does not adjust her reference point in money to the situation, her utility would be given by:

$$
u((1,0,-5)|(1,0,0)) = 4 * 1 + 4 * 0 - 5 + v(4 * 1 - 4 * 1) + v(4 * 0 - 4 * 0) + v(-5 - 0)
$$
$$
u((1,0,-5)|(1,0,0)) = 4 - 5 - 5 = -6
$$
$$
u((0,1,-2)|(1,0,0)) = 4 * 0 + 4 * 1 - 2 + v(4 * 0 - 4 * 1) + v(4 * 1 - 4 * 0) + v(-2 - 0)
$$
$$
u((0,1,-2)|(1,0,0)) = 4 - 2 - 12 + 4 -2 = -8
$$

In conclusion, as

$$
u((0,1,-2)|(1,0,0)) = -8 < -6 = u((1,0,-5)|(1,0,0))
$$

she would not exchange her mug for a pen plus 3dollars. The intuition is because she does not adjust her reference point in money, such as (r1, r2, r3) = (1, 0, -5), the small amount of money 3dollars will still be felt like a loss compared to the reference point r3 = 0. On the opposite, if the reference point in money is adjusted, then the small amount of money 3 dollars will be felt like a gain. Therefore, the mug owner will experience still two losses he will not exchange. 

2-

a)

As stated in the paper, the initial endowment is (0,0). In addition, the assumptions are:
** 1. m(c) = $c_1$ + $c_2$
** 2. $c_1$ {0, 1} indicates whether the consumer get a pair of shoes.
** 3. $c_2$ = -p if the consumer pays price p.

$$ 
\mu(x) = \begin{cases}  \eta x\,  & ,x > 0 \\ 
\eta\lambda x\,  & , x \le 0  \end{cases}
$$

Therefore, the consumer buys shoes for all prices $p$ if:

$$
u((1, -p)|(0, 0)) > u((0, 0)|(0, 0))
$$

$$
u((1, -p)|(0, 0)) = 1 - p + \eta - \eta\lambda p > 0 = u((0,0)|(0,0))
$$

By resolving the equation we get:

$$
1 + \eta - p(1 + \eta\lambda) > 0
$$

$$
1 + \eta > p(1 + \eta\lambda)
$$

$$
p < \frac{1 + \eta}{1 +\eta\lambda}
$$
Hence

$$
p < p_{min} \equiv\frac{1 + \eta}{1 +\eta\lambda}
$$
b)

Now, the consumer never buys shoes for all prices p if:

$$
u((1, -p)|(1, -p)) < u((0, 0)|(1, -p)))
$$

$$
u((1, -p)|(1, -p)) = 1 - p
$$

$$
u((0, 0)|(1, -p)) = -\eta\lambda + \eta p
$$

Therefore, by replacing the terms into the first inequation:

$$
u((1, -p)|(1, -p)) = 1 - p < -\eta\lambda + \eta p = u((0, 0)|(1, -p))
$$

$$
1 - p + \eta\lambda - \eta p < 0
$$

$$
1 + \eta\lambda < p(1 + \eta)
$$

$$
p > \frac{1 + \eta\lambda}{1 + \eta}
$$
Hence

$$
p > p_{max} \equiv \frac{1 + \eta\lambda}{1 + \eta}
$$

c)

Assume that if the consumer expects to buy with probability $q$ $\in$ [0,1] and $p_{min}$ < p < $p_{max}$ then the utility from buying is given by:

$$
u((1, -p)|(0, 0)) = 1 - p + (1-q)(\eta - \eta\lambda p) = 1 - p +(1 - q)\eta(1-\lambda p)
$$

And the utility from not buying is given by:

$$
q * u((0,0)|(1,-p)) = q *(-\eta\lambda + \eta p) = q\eta(p-\lambda)
$$

By equalizing the two equations above and isolating the q, we get:

$$
1 - p  + (1 - q)\eta(1-\lambda p) =  q\eta(p-\lambda)
$$
$$
1 - p + \eta - \eta\lambda p - q\eta + q\eta\lambda p = q\eta p - q \eta\lambda
$$

$$
q\eta\lambda p + q\eta\lambda - q\eta - q\eta p = \eta\lambda p - \eta + p -1
$$

$$
q(\eta\lambda p + \eta\lambda)-q(\eta +\eta p) = p(1+\eta\lambda)-(1+\eta)
$$
$$
q(\eta\lambda p + \eta\lambda-\eta -\eta p) = (1+\eta\lambda)p - (1 +\eta)
$$
$$
q(\eta(\lambda-1)(p+1)) = (1+\eta\lambda)p - (1 +\eta)
$$
$$
q = \frac{(1+\eta\lambda)p - (1 +\eta)}{\eta(\lambda-1)(p+1)}
$$

3-

a)

The probability that the consumer buys from firm i over firm j is given by

$$
Pr(s_i \ge s_j) = Pr[x_j - p_j - L(p_j, p^e) \le x_i - p_i - L(p_i, p^e) ]
$$
where L($p_i$, $p^e$) = max{0,$\lambda$ ($p_i$ - $p^e$)}, $\lambda$ > 0

$$
= Pr[x_j \le x_i - (p_i - p_j) - L(p_i,p^e) + L(p_j,p^e)] = F(x_i - (p_i - p_j) - L(p_i,p^e) + L(p_j,p^e))
$$

The proportion of consumers who buys from firm j is given by:

$$
Pr(s_i \ge max_{j \neq i} s_j) = \int\space \prod_{j \neq i} F[x_i - (p_i - p_j) - L(p_i,p^e) + L(p_j,p^e)]f(x_i)dx_i
$$

b)

Let the expected demand of firm $i$ be given by the proportion of consumers who prefer that brand times the number of consumers $L$:

$$
D_i(p_i, p_j) = Pr(s_i \ge max_{j \neq i} s_j)L
$$

The profit function of firm $i$ is given by:

$$
\pi_i(p_i, p_j) = (p_i - c_i) * D_i(p_i, p_j)
$$

The profit function of firm $i$ is differentiable with respect to $p_i$

$$
\frac{\delta pi_i(p_i, p_j)}{\delta p_i}: D_i(p_i, p_j) + (p_i - c_i) \frac{\delta D_i(p_i, p_j)}{\delta p_i} = 0
$$

$$
p_i - c_i = - \frac{D_i(p_i, p_j)}{\frac{\delta D_i(p_i,p_j)}{\delta p_i}}
$$

c)


$$
D_i(p_i, p_j) = Pr(s_i \ge max_{j \neq i} s_j)L
$$

$$
D_i(p_i, p_j) = L \int\space \prod_{j \neq i} F[x_i - (p_i - p_j) - L(p_i,p^e) + L(p_j,p^e)]f(x_i)dx_i
$$

Assuming that there is no loss aversion (i.e. when $\lambda$ = 0)

$$
D_i(p_i, p_j) = L \int\space \prod_{j \neq i} F[x_i - (p_i - p_j)]f(x_i)dx_i
$$

$$
D_i(p_i, p_j) = L \int\space F[x_i - (p_i - p_j)]f(x_i)dx_i
$$

Differentiating the last equation with respect to $p_i$ we have that:

$$
\frac{\delta D_i}{\delta p_i} = -L \int\space f(x_i - (p_i - p_j))f(x_i)dx_i
$$

Therefore:

$$
D_i(p_i, p_j) = L \int\space F[x_i - (p_i - p_j)]f(x_i)dx_i = L/n
$$

Thus the equilibrium mark-up is given by:

$$
p_i - c_i = - \frac{L/n}{-L \int\space f(x_i - (p_i - p_j))f(x_i)dx_i}
$$

$$
p_i - c_i =  \frac{1}{n \int\space f(x_i - (p_i - p_j))f(x_i)dx_i} = \frac{1}{n*M(n)}
$$

where $M(n)$ = $\int\space f(x_i - (p_i - p_j))f(x_i)dx_i$

**NOT WORKING**

4-

a)

The demand is:

$$
D_i(p_i, p_{-i}) = \frac{e^\frac{q_i - p_i}{\sigma}}{\sum_{j = 1}^{n}e^\frac{q_j - p_j}{\sigma}}
$$
The equilibrum price must satisfy the following condition:

$$
p^* = \arg \max_{p_{i}} (p_i - c)D_i(p_i,p_{-i}^*)
$$
Thus, replace $D_i(p_i,p_{-1}^*)$:

$$
p^* = \arg \max_{p_{i}} (p_i - c) \frac{e^\frac{q_i - p_i}{\sigma}}{\sum_{j = 1}^{n}e^\frac{q_j - p_j}{\sigma}}
$$
As we assume that all the quantities are the same, $q$ and in a symmetric equilibrum every firm will choose the same price $p^*$, then:

$$
p^* = \arg \max_{p_{i}} (p_i - c) \frac{e^\frac{q - p_i}{\sigma}}{\sum_{j = 1}^{n}e^\frac{q - p^*}{\sigma}}
$$
a)
utility is $u_{i} = q_{i}-p_{i}+\varepsilon_{i}$
Therefore the probability that a consumer chose brand i over j is 
$$Pr(s_{i} \ge max_{j\ne i} s_{j}) =\int\space [\prod_{j\ne i}(\sigma^{-1}(p_{j}-p_{i})+\varepsilon_{i})]f(\varepsilon_{i})d\varepsilon_{i}$$
Thus the expected demand is 
$$D_{i}(p_{1},...,p_{n}) = Pr(s_{i} \ge max_{j\ne i} s_{j})$$
The profit is therefore 
$$\pi_{i}(p_{1},...,p_{n}) = (p_{i}-c)D_{i}(p_{1},...,p_{n})$$
The first order condition from this the formula above is 
$$p_{i} - c = \frac{D_i(p_i,...p_n)}{\delta D_i/\delta p_i} $$
if all firm charge the same price p* and all have the same quality q then we get
$$\delta D_i/\delta p_i = -(n-1)/q\int[F(\varepsilon_i)]^{n-2}[f(\varepsilon_i)]^{n-2}d\varepsilon_i$$
by substituting the value p_i = p into the demand Di we get 
$$D_i(p) = \int[F(\varepsilon_i)]^{n-1}[f(\varepsilon_i)]^{n-1}d\varepsilon_i$$
The value that we have for the inital demand is $D_i(p_i, p_{-i}) = \frac{e^\frac{q_i - p_i}{\sigma}}{\sum_{j = 1}^{n}e^\frac{q_j - p_j}{\sigma}}$
Thus $$ln(D_i)' = ((p-p_i)/\sigma)/\sigma$$

and if we take into account that $p_i = p_{-i} = p^{*}$, then $D_i = 1$
Therefore 
$$p^{*} - c = \frac{1}{\frac{(n-1)}{\sigma}}*\frac{p^{*}-p^{*}}{\sigma}/\sigma \\ ;p^{*} = \frac{1}{n-1}*\sigma$$
**5-**

a)
In T = 0, the firm can set the price of the based good and of the the add-on (hidden complementary), in this scenario it can decided to shrouded the add-on price, in our case sigma. From this moment on, consumers naive (unaware of hidden fees), and sophisticated (aware of hidden fees), will each chose their strategy. An example of noise manipulation by a firm would be in the case of printer sales. With a low based price for the printer, if the company does not share the shrouded hidden price (in this case ink cartridges), and offer a discount on their based product, a naive consumer might jump on the occasion thinking that he made a great deal. However on the long run he will have to pay supplementary price higher than the initial price.
(Perloff & Salop 1985), the expected profit are:
$$\pi_i(p_1,...,p_n) = (p-c)D_i(p_1,...,p_n)\space where$$
Where p = price, c = cost, D_i = demand.
in our case:
$$\pi = p - c = p - c(\sigma) = \frac{1}{2\gamma}(\sigma-\sigma^{*})^2$$
if we derivate in respect to $c(\sigma)$ we will find the optimal cost
$$\frac{\delta\pi}{\delta\sigma} = \frac{\sigma-\sigma^{*2}}{\gamma}$$
if all firm choose the same level of complexity then 
$$\frac{\delta\pi}{\delta\sigma} = \frac{\sigma-\sigma^{2}}{\gamma}$$
Therefore the optimal level of complexity cannot be 0 as:
$$\frac{\delta\pi}{\delta\sigma} = \frac{\sigma-\sigma^{2}}{\gamma} = \sigma^{*} < 0$$

b)
(Perloff & Salop 1985), the expected profit are:
$$\pi_i(p_1,...,p_n) = (p-c)D_i(p_1,...,p_n)\space where$$
If we $D_i = 1 then, \pi = p-c$
In our case :
$$\pi = p - c(\sigma)$$
if $p \le q$ then
$$$$
if $p \le q + c(\sigma)$ then
$$$$
if $p \le q - c(\sigma)$

d)
In a situation where alpha is close to 1, we assume that the market is full of naive consumer. In such scenario, (Gabaix and Libson 2005), explains that a myope consumer will be unaware of add-on unless they are showed a listing price for it (ex. advertising). In such scenario, Those consumers will take all the steps needed to avoid paying for the company advertising price. This situation will thus, diminish the company profits. Thereby, the best strategy would be to propose a lower based good price.

e)
In a situation where alpha is close to 0, the population is full of sophisticated consumers.(Gabaix and Libson 2005), explains that in such scenario, a company that wishes to maximize its profit should propose a high quality product at a high based price with a lower add-on price.

